simulation:
  n_spectra: 100
  n_bins: 20000  # Elena's eyeballed estimation from Ben's thesis
  bin_width_hz: 100.0
  f_start_hz: 5.7161e9
  tune_step_bins: 100
  rng_seed: 1234
  noise_sigma: 1.0

input:
  read_input: true
  directory: "output/qshs_to_FOX/run_21.07.2026_08.46.02"
  input_file_name: "converted_spectra.h5"

injection:
  enabled: true
  # f_axion_hz: 5.725e9   # optional; if omitted, placed at mid-span
  sigma_hz: 2500.0
  total_power: 20.0

quality:
  max_power_filter: true            # filter the spectra for max mean power 
  p_max: 1e-8                       # max power allowed
  noise_filter: true                # filter the spectra for noise
  rms_max: 3.0                  # max RMS allowed
  nan_fail: true                    # drop spectra with NaNs/inf
  robust: false                     # use median+MAD instead of mean+std
  small_bandwidth_filter: true      #filter the spectra for small bandwidths
  bw_min: 0.00027                   # min bandwidth allowed (same as QSHS)
  bandwidth_zeros_filter: true      # filter the spectra for bandwdith data being arrays of zeros
  res_freq_zeros_filter: true       # filter the spectra for res_freq data being arrays of zeros
  bad_time_filter: true            # filter spectra within a known bad time frame
  start_time: ["2026-01-31 09:55:41" ] # List of start times of the known bad data in format YYYY-MM-DD HH:MM:SS
  end_time: ["2026-02-01 00:10:58"] # List of end times of the known bad data in format YYYY-MM-DD HH:MM:SS


baseline:
  sg_window_warm: 351
  sg_poly_warm: 4
  sg_window_cold: 351
  sg_poly_cold: 4

rebin:
  C: 10
  K: 9

detection:
  target_snr: 5.0
  confidence: 0.95
  snr_eff: 0.90
  g0: 1.0

output:
  save_data: false      # save per-spectrum PNGs + spectra.npz
  combined_plot: false  # save combined PNG of all spectra
  offset_combined_plot: false # save combined PNG of all spectra with offset
  plots_step: 1         # plot every Nth spectrum
  # max_plots: 100      # optional cap
  root: "output"        # base output folder
  subdir_prefix: "run"  # subfolder prefix: run_<timestamp>
